name: ddiff
channels:
  - pytorch
  - nvidia
 # - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision==0.15.2
  - torchaudio==2.0.2
  - pytorch-cuda=11.7
  - accelerate
  - einops
  - numpy<2
  - pillow
  - scipy
  - tqdm
  - pip
  - pip:
    - ema-pytorch>=0.4.2
    - pytorch-fid
    - toml
    - wandb==0.17.3


