[unet_params]
dim = 64
dim_mults = [1, 2, 4, 8]
channels = 3

[diffusion_params]
image_size = 32
timesteps = 1000
beta_schedule = "linear"

[trainer_params]
folder = "./data"
train_lr = 5e-5
train_batch_size = 64
train_num_steps = 100000
save_and_sample_every = 1
num_samples = 1
results_folder = "./results"

[sample]
batch_size = 20
