[unet_params]
dim = 64
dim_mults = [1, 2, 4]
channels = 3

[diffusion_params]
image_size = 32
timesteps = 1000
beta_schedule = "linear"

[trainer_params]
folder = "./data"
train_lr = 1e-4
train_batch_size = 128
train_num_steps = 100000
save_and_sample_every = 1000
num_samples = 25
results_folder = "./results"

[sample]
batch_size = 20