[unet_params]
dim = 64
dim_mults = [1, 2, 4, 8]
channels = 3

[diffusion_params]
image_size = 32
timesteps = 1000
beta_schedule = "linear"

[trainer_params]
folder = "./data"
train_lr = 5e-5
train_batch_size = 128
train_num_steps = 50000
save_and_sample_every = 5000
num_samples = 16
results_folder = "./results"
num_train_fid_samples = 2
num_test_fid_samples = 10000
load_milestone = 0
load_path = "None"
load_from_config = false

[subset_params]
subset_size = 4000
subset_sizes = [4000, 8000, 12000]
num_train_fid_samples = 10

[sample]
pretrained_path = "None"
batch_size = 32
