[unet_params]
dim = 64
dim_mults = [1, 2, 4, 8]
channels = 3

[diffusion_params]
image_size = 32
timesteps = 1000
sampling_timesteps = 200
beta_schedule = "linear"

[trainer_params]
folder = "./data"
train_lr = 2e-4
train_batch_size = 128
train_num_steps = 50000
save_and_sample_every = 5000
num_samples = 9
results_folder = "./results"
num_train_fid_samples = 2000
num_test_fid_samples = 10000
load_path = "results/25000_2025-05-08_23-17-41/model-best.pt"
load_from_config = false

[subset_params]
subset_size = 1000
subset_sizes = [1000, 25000, 50000]
num_train_fid_samples = 2000

[sample]
pretrained_path = "None"
batch_size = 32
