wandb_version: 1

batch_size:
  desc: null
  value: 16
gradient_accumulate_every:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0001
train_num_steps:
  desc: null
  value: 100000
ema_decay:
  desc: null
  value: 0.995
image_size:
  desc: null
  value:
  - 32
  - 32
num_samples:
  desc: null
  value: 25
_wandb:
  desc: null
  value:
    python_version: 3.8.20
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1746367613
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 71
      2:
      - 1
      - 41
      - 49
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.8.20
      5: 0.17.3
      8:
      - 5
      13: darwin-x86_64
